name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Deps
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
